### ISSUE TITLE
some error can help?

### ISSUE THREAD

**Issue by X0811** [Alexander9673/GTBot#3]
![Command Prompt 3_19_2021 12_00_45 PM](https://user-images.githubusercontent.com/72257246/111733926-95445280-88ab-11eb-9f2a-5496f1396a5c.png)

**Comment by Syn9673** [comment]
install the necessary packages, by doing `npm install`

**Comment by X0811** [comment]
![Command Prompt 3_19_2021 8_03_12 PM](https://user-images.githubusercontent.com/72257246/111784943-934fb300-88ee-11eb-80e7-88f89f4815db.png)
this i dont know how to fix it

**Comment by Syn9673** [comment]
`npm install ws @types/ws`
