### ISSUE TITLE
Error when proxy is connecting

### ISSUE THREAD

**Issue by Gold512** [Alexander9673/GTBot#8]
I just get the error 
``` 
Worker [1]: Socket {
  client: Native {
    ip: 'undefined',
    port: NaN,
    instance: Client { [ip]: [Getter/Setter], [port]: [Getter/Setter] }     
  },
  initialized: true,
  connected: true,
  ip: '127.0.0.1'
} disconnected from ENet Server
Worker [1]: Socket Closed with Code: 1005 with reason: None
```
and the proxy is unable to connect, anyone knows why this happens

**Comment by Syn9673** [comment]
Probably due to outdated code. I havn't updated this code in almost 2 years? Also, provide more context on where the error happens.

**Comment by Gold512** [comment]
It happens when i try to connect from the website. It seems to manage to connect to cors but after awhile this error appears in the console of the proxy process

**Comment by Syn9673** [comment]
I could whip you up with a fixed & improved version of this. But obviously not for free

**Comment by Gold512** [comment]
After some trial and error, changing the websocket init request seems to make the enet connection work. I'll just try and write my own client code. Thanks for taking the time to reply anyways.
